version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build/

hooks:
  BeforeInstall:
      - location: server/scripts/beforeInstall.bash
        runas: root
  AfterInstall:
      - location: server/scripts/afterInstall.bash
        runas: root
